#!/bin/sh

. ios-build-env.sh

case $PLATFORM in
    (iPhoneOS) sdkmin=-miphoneos-version-min=$SDKMIN ;;
    (*) sdkmin=-mios-simulator-version-min=$SDKMIN
esac

exec clang-ios \
-fobjc-arc \
-fmessage-length=0 \
-std=gnu99 \
-fexceptions \
-fasm-blocks \
-fstrict-aliasing \
-fobjc-abi-version=2 \
-fobjc-legacy-dispatch \
$sdkmin \
-Xclang -fobjc-runtime-has-weak \
"$@"
