#!/bin/sh

Usage()
{
    echo >&2 "Usage: copy-headers-from-to Headers-dir target-dir"
}

if [ $# -ne 2 ]
then
    Usage
    exit 1
fi

from=$1
to=$2
shift 2
if [ -z "$from" ] || [ -z "$to" ]
then
    Usage
    exit 1
fi
case $from in (/*) ;; (*) from=./$from; esac
case $to in (/*) ;; (*) to=./$to; esac

cd "$from"

frameworkname=$(
    while true
    do
        pwd=$(pwd)
        case $pwd in
            (/) break ;;
            (*.framework)
                printf '%s\n' "$pwd"
                break
                ;;
        esac
        cd ..
    done
)

if [ -z "$frameworkname" ]
then
    echo >&2 "Could not determine framework name."
    exit 1
fi

cp ./*.h "$to"
