#!/bin/sh

: ${PLATFORM=iPhoneOS}
: ${SDKVERSION=6.1}

fwdir=/Applications/Xcode.app/Contents/Developer/Platforms/$PLATFORM.platform/Developer/SDKs/$PLATFORM$SDKVERSION.sdk/System/Library/Frameworks
targetdir=$HOME/tmp/ios-headers

rm -rf "$targetdir"
mkdir -p "$targetdir"
for file in "$fwdir"/*
do
    fw=${file##*/}
    fw=${fw%.framework}
    mkdir "$targetdir/$fw"
    cp "$file"/Headers/* "$targetdir/$fw"
done
