#!/bin/sh

: ${PLATFORMS=iPhoneOS iPhoneSimulator}
: ${SDKVERSIONS=6.1}

for platform in $PLATFORMS
do
    for sdkversion in $SDKVERSIONS
    do
        fwdir=/Applications/Xcode.app/Contents/Developer/Platforms/$platform.platform/Developer/SDKs/$platform$sdkversion.sdk/System/Library/Frameworks
        targetdir=$HOME/tmp/ios-headers/$platform/$sdkversion

        rm -rf "$targetdir"
        mkdir -p "$targetdir"
        find "$fwdir" -type d -name Headers -exec \
            ./copy-headers-from-to {} "$targetdir" \;
    done
done
